spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: hikaripool
      max-lifetime: 1800000
      connection-timeout: 30000
